version: '3.8'

services:
  web:
    container_name: scheduler
    build:
      context: .
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "8000:8000"
    networks:
      - scheduler

  db:
    image: postgres:14
    container_name: scheduler-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=db
      - POSTGRES_PASSWORD=db
    volumes:
      - scheduler-db:/var/lib/postgresql/data
      - ./initdb/scheduler_schema.sql:/docker-entrypoint-initdb.d/1-scheduler_schema.sql
    networks:
      - scheduler

  mailpit:
    image: axllent/mailpit
    restart: always
    volumes:
      - ./mailpit:/data
    ports:
      - 8025:8025
      - 1025:1025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATA_FILE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    networks:
      - scheduler

  mariadb:
    image: docker.io/bitnami/mariadb:11.1
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_moodle
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - 'mariadb_data:/bitnami/mariadb'
    networks:
      - scheduler

  moodle:
    image: docker.io/bitnami/moodle:4.3
    ports:
      - '8888:8080'
    environment:
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'moodle_data:/bitnami/moodle'
      - 'moodledata_data:/bitnami/moodledata'
    depends_on:
      - mariadb
    networks:
      - scheduler

networks:
  scheduler:
    name: scheduler
    driver: bridge

volumes:
  scheduler-db:
  mariadb_data:
  moodle_data:
  moodledata_data:
